export const PageTitles = {
  LOGIN: "ADMIN LOGIN",
  HOME: "Create Invoice",
  CUSTOMER_DETAILS: "Customer Details",
  FUNCTION_DETAILS: "Function Details",
  MENU_DETAILS: "Menu Details",
  MENU_ITEMS: "Menu Items",
  INVOICE: "INVOICE",
  HISTORY: 'HISTORY'
};

export const ButtonLabels = {
  RESET: "Reset",
  SUBMIT: "Submit",
  LOGIN: "Login",
};

export const ReviewPageLiterals = {
  TITLE1: "H.A.",
  TITLE2: "BRIYANI CATERING",
  INVOICE_NO: "Invoice No:",
  INVOICE_DATE: "Invoice Date",
  FUNCTION_NAME: "Function:",
  FUNCTION_DATE: "Function Date:",
  TOTAL_UNITS: "Total Units:",
  GST_NO:'GST: 33BHFPH0925J1ZM',
  DESCRIPTION:'DESCRIPTION',
  UNITS: 'UNITS',
  AMOUNT: 'AMOUNT'
};

export const menuCombosList = [
  {
    comboName: "Elite Mutton Briyani Combo",
    items: [
      "Tandoori Chicken",
      "Full Goat (Extra charges)",
      "Rashamalai / Gulab Jamun / Furni Sweet / Bread Halwa",
      "Idiyappam",
      "Naan",
      "Fish Fry (1 piece )",
      "Prawn Fry",
      "Paneer Butter Masala",
      "Meeta Khana",
      "Kesari Sweet",
      "Welcome Drink (Watermelon, Others - Extra)",
      "Mutton Briyani",
      "Chicken 65 (2 pieces)",
      "Chappati",
      "Rumani Roti",
      "Pepper Chicken Gravy",
      "Brinjal Curry",
      "Onion Raita",
      "Fruit Salad",
      "Beeda",
      "Abukota Ice cream",
      "Water Bottle 300ml",
      "Banana Leaf",
      "Service Boys",
      "Panjimithai",
      "Choclate Fountain",
      "Popcorn",
      "Boat Halwa",
      "Mutanjan Sweet",
      "Butter Chicken",
      "Transport free for 5km",
    ],
  },

  {
    comboName: "Budget Mutton Briyani Combo",
    items: [
      "Welcome Drink (Watermelon, Others - Extra)",
      "Mutton Briyani",
      "Chicken 65 (2 pieces)",
      "Rumani Roti",
      "Pepper Chicken Gravy",
      "Bread Halwa",
      "Brinjal Curry",
      "Onion Raita",
      "Fruit Salad",
      "Beeda",
      "Abukota Ice cream",
      "Water Bottle 300ml",
      "Banana Leaf",
      "Service Boys",
      "Panjimithai",
      "Choclate Fountain",
      "Popcorn",
      "Transport free for 5km",
    ],
  },
  {
    comboName: "Elite Chicken Briyani Combo",
    items: [
      "Tandoori Chicken",
      "Full Goat (Extra charges)",
      "Rashamalai / Gulab Jamun / Furni Sweet / Bread Halwa",
      "Idiyappam",
      "Naan",
      "Fish Fry (1 piece )",
      "Prawn Fry",
      "Paneer Butter Masala",
      "Meeta Khana",
      "Kesari Sweet",
      "Welcome Drink (Watermelon, Others - Extra)",
      "Chicken Briyani",
      "Chicken 65 (2 pieces)",
      "Chappati",
      "Rumani Roti",
      "Pepper Chicken Gravy",
      "Brinjal Curry",
      "Onion Raita",
      "Fruit Salad",
      "Beeda",
      "Abukota Ice cream",
      "Water Bottle 300ml",
      "Banana Leaf",
      "Service Boys",
      "Panjimithai",
      "Choclate Fountain",
      "Popcorn",
      "Boat Halwa",
      "Mutanjan Sweet",
      "Butter Chicken",
      "Transport free for 5km",
    ],
  },

  {
    comboName: "Budget Chicken Briyani Combo",
    items: [
      "Welcome Drink (Watermelon, Others - Extra)",
      "Chicken Briyani",
      "Chicken 65 (2 pieces)",
      "Rumani Roti",
      "Pepper Chicken Gravy",
      "Bread Halwa",
      "Brinjal Curry",
      "Onion Raita",
      "Fruit Salad",
      "Beeda",
      "Abukota Ice cream",
      "Water Bottle 300ml",
      "Banana Leaf",
      "Service Boys",
      "Panjimithai",
      "Choclate Fountain",
      "Popcorn",
      "Transport free for 5km",
    ],
  },
];
